# Generated by Django 4.1.1 on 2022-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0002_employeeprofile_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='user_nation_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
