# Generated by Django 4.1.2 on 2022-10-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0003_alter_employeeprofile_user_nation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='user_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='user_birthdate',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='user_nation_id',
            new_name='nation_id',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='user_telephone',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user_position',
        ),
    ]
