# Generated by Django 4.1.2 on 2022-10-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0004_rename_user_address_employeeprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
