# Generated by Django 4.1.2 on 2022-10-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0005_companyposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_data.companyposition')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_data.employeeprofile')),
            ],
        ),
    ]
