# Generated by Django 4.1.2 on 2022-10-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0006_profileposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileposition',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee_data.companyposition'),
        ),
        migrations.AlterField(
            model_name='profileposition',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee_data.employeeprofile'),
        ),
    ]
