# Generated by Django 4.1.2 on 2022-11-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0025_alter_drawingassignment_detail_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(blank=True, null=True, upload_to='file')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(blank=True, null=True, upload_to='file')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_section.purchaseordertitle')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_section.filedetail')),
                ('quotation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_section.quotationfile')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_section.picturefile')),
                ('po_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_section.podocumentfile')),
                ('purchase_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_section.purchaseordertitle')),
                ('quotation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_section.quotationfile')),
            ],
        ),
        migrations.CreateModel(
            name='PoDocumentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_section.filedetail')),
                ('po_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_section.podocumentfile')),
            ],
        ),
    ]
