# Generated by Django 4.1.2 on 2022-10-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_section', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkshopJob',
        ),
    ]
