# Generated by Django 4.1.1 on 2022-10-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('picture4', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('picture5', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('drawing1', models.FileField(blank=True, null=True, upload_to='file')),
                ('drawing2', models.FileField(blank=True, null=True, upload_to='file')),
                ('drawing3', models.FileField(blank=True, null=True, upload_to='file')),
                ('drawing4', models.FileField(blank=True, null=True, upload_to='file')),
                ('drawing5', models.FileField(blank=True, null=True, upload_to='file')),
            ],
        ),
    ]
