# Generated by Django 4.1.1 on 2022-10-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingfile',
            name='customer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='drawingfile',
            name='drawing_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='drawingfile',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
