# Generated by Django 4.1.1 on 2022-10-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0002_drawingfile_customer_drawingfile_drawing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingfile',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
