# Generated by Django 4.1.1 on 2022-10-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0003_alter_drawingfile_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingfile',
            name='draftsman',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
