# Generated by Django 4.1.1 on 2022-10-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0004_drawingfile_draftsman'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingfile',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingfile',
            name='process_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
