# Generated by Django 4.1.1 on 2022-10-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0006_rename_drawing_status_drawingfile_drawing1_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingfile',
            name='drawing1_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drawingfile',
            name='drawing2_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drawingfile',
            name='drawing3_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drawingfile',
            name='drawing4_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drawingfile',
            name='drawing5_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
