# Generated by Django 4.1.2 on 2022-10-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_section', '0002_delete_workshopjob'),
        ('customer_section', '0001_initial'),
        ('employee_data', '0007_alter_profileposition_position_id_and_more'),
        ('design_section', '0007_drawingfile_drawing1_name_drawingfile_drawing2_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(blank=True, null=True, upload_to='file')),
                ('detail', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='design_section.drawingdetail')),
            ],
        ),
        migrations.CreateModel(
            name='JobTiltles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('process_date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='customer_section.customers')),
            ],
        ),
        migrations.CreateModel(
            name='PictureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('detail', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='design_section.jobtiltles')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee_data.employeeprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='DrawingFile',
        ),
        migrations.AddField(
            model_name='jobdrawing',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='design_section.jobtiltles'),
        ),
        migrations.AddField(
            model_name='jobdrawing',
            name='picture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='design_section.picturedetail'),
        ),
    ]
