# Generated by Django 4.1.2 on 2022-10-21 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design_section', '0009_rename_profilejob_userjob_remove_userjob_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtiltles',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
