# Generated by Django 4.1.2 on 2022-10-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_section', '0001_initial'),
        ('design_section', '0010_alter_jobtiltles_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtiltles',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer_section.customers'),
        ),
    ]
