# Generated by Django 4.1.2 on 2022-10-25 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design_section', '0011_alter_jobtiltles_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(blank=True, null=True, upload_to='file')),
                ('detail', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PictureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='picturedetail',
            name='detail',
        ),
        migrations.AddField(
            model_name='picturedetail',
            name='status',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True)),
                ('submitter_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
