# Generated by Django 4.1.2 on 2022-10-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0012_drawingfile_picturefile_remove_picturedetail_detail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobDrawing',
            new_name='JobFiles',
        ),
        migrations.RemoveField(
            model_name='drawingdetail',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='drawingdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drawingdetail',
            name='path',
        ),
        migrations.RemoveField(
            model_name='drawingdetail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='drawingfile',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='picturedetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='picturedetail',
            name='path',
        ),
        migrations.RemoveField(
            model_name='picturedetail',
            name='status',
        ),
        migrations.AddField(
            model_name='drawingdetail',
            name='detail_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='design_section.filedetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drawingdetail',
            name='drawing_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='design_section.drawingfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picturedetail',
            name='detail_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='design_section.filedetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picturedetail',
            name='picture_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='design_section.picturefile'),
            preserve_default=False,
        ),
    ]
