# Generated by Django 4.1.2 on 2022-10-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0013_rename_jobdrawing_jobfiles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetail',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
