# Generated by Django 4.1.2 on 2022-10-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_section', '0001_initial'),
        ('design_section', '0014_filedetail_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobTiltles',
            new_name='JobTiltle',
        ),
    ]
