# Generated by Django 4.1.2 on 2022-10-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0015_rename_jobtiltles_jobtiltle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobFiles',
            new_name='JobFile',
        ),
    ]
