# Generated by Django 4.1.2 on 2022-10-27 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0017_alter_jobfile_drawing_id_alter_jobfile_picture_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfile',
            name='drawing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='design_section.drawingfile'),
        ),
        migrations.AlterField(
            model_name='jobfile',
            name='picture_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='design_section.picturefile'),
        ),
    ]
