# Generated by Django 4.1.2 on 2022-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0018_alter_jobfile_drawing_id_alter_jobfile_picture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetail',
            name='status',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
