# Generated by Django 4.1.2 on 2022-10-31 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0021_remove_filedetail_reciever_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(max_length=200)),
                ('receiver_username', models.CharField(max_length=200)),
                ('job_state', models.CharField(max_length=200)),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='design_section.filedetail')),
                ('drawing_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='design_section.drawingfile')),
            ],
        ),
    ]
