# Generated by Django 4.1.2 on 2022-10-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0022_drawingassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetail',
            name='submit_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
