# Generated by Django 4.1.2 on 2022-10-31 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_section', '0024_alter_drawingassignment_receiver_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingassignment',
            name='detail_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='design_section.filedetail'),
        ),
    ]
